apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-nodejs-app-set
spec:
  generators:
  - git:
      repoURL: https://github.com/Enferium/argo-applicationset-test
      revision: HEAD
      directories:
      - path: ./*
        template:
          metadata:
            name: '{{path.basename}}'
          spec:
            project: default
            source:
              repoURL: https://github.com/Enferium/nodejs-k8s-argo-helm-helloworld
              targetRevision: HEAD
              path: '{{path}}'
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{path.basename}}'